### ISSUE TITLE
[Design] Are setters in EdgeApplicationConnector necessary?

### ISSUE THREAD

**Issue by smarianimore** [openness-4-java/openness-connector#6]
Setters are always dangerous, are these needed? Does it make sense to change such members after creation?

**Comment by piconem** [comment]
The following set methods have been removed.

- setAuthorizedApplicationConfiguration
- setEdgeApplicationServiceEndpoint

It wasn't correct to allow to externally change authConfiguration and opennessEndpoint at runtime. If required a new Connector instance should be created avoiding potential inconsistency during the execution.
